version: '3'
services:
  mysql:
    container_name: mysql
    build: ./database
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample_db
    ports:
      - '3306:3306'
